global:
  scrape_interval: 15s  # Intervalo de coleta de métricas

scrape_configs:
  - job_name: 'redis'
    static_configs:
      - targets: ['localhost:9121']  # Nome do serviço Redis Exporter

  - job_name: 'node_app'
    static_configs:
      - targets: ['localhost:8081']  # Nome do serviço Node.js (se você precisar coletar as métricas)

  - job_name: 'go_app'
    static_configs:
      - targets: ['localhost:8085']
